import type { DailyQuoteBundle } from './types';

// This is the single source of truth for all content.
// It's a large, static array of daily bundles. The app will cycle through this
// list deterministically based on the day of the year.
export const CONTENT_ARCHIVE: Omit<DailyQuoteBundle, 'date'>[] = [
  // DAY 1
  {
    languages: {
      "en": {
        "quoteOfTheDay": [
          "The only way to do great work is to love what you do. – Steve Jobs",
          "The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
          "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt"
        ],
        "interestingKnowledge": [
          { "title": "The Eiffel Tower Can 'Grow' in the Summer", "text": "Constructed from wrought iron, the Eiffel Tower is a remarkable example of 19th-century engineering. Its very material gives it a surprising characteristic: it changes height with the seasons. This phenomenon, known as thermal expansion, causes the iron to expand when heated and contract when cooled. On a hot summer day in Paris, this expansion can result in the tower's peak rising by as much as 15 centimeters (about 6 inches) compared to its height in winter. Gustave Eiffel ingeniously accounted for this, incorporating expansion joints that allow the structure to flex without sustaining damage." },
          { "title": "Octopuses Have Three Hearts and Blue Blood", "text": "The octopus possesses a fascinating and highly efficient circulatory system. Two of its three hearts are dedicated to pumping blood through the gills, where it picks up oxygen, while the third, larger heart circulates this oxygenated blood to the rest of the body. Their blood is blue due to the presence of hemocyanin, a copper-based protein, which is more efficient at transporting oxygen in cold, low-oxygen environments compared to the iron-based hemoglobin found in human blood. This unique biology is a key reason for their survival in diverse marine ecosystems." },
          { "title": "Honey Never Spoils", "text": "The remarkable longevity of honey is a result of its unique chemical properties. Its extremely low water content creates an environment too arid for bacteria and microorganisms to survive. Furthermore, honey is highly acidic, with a pH that is inhospitable to most microbes. Its most fascinating defense is an enzyme called glucose oxidase, added by bees. When honey is exposed to moisture, this enzyme produces small amounts of hydrogen peroxide, a powerful antimicrobial agent. This natural preservative system is so effective that archaeologists have discovered edible honey in ancient Egyptian tombs over 3,000 years old." },
          { "title": "The Shortest War in History Lasted 38 Minutes", "text": "The Anglo-Zanzibar War holds the record for the shortest war in recorded history, fought on August 27, 1896. The conflict erupted after the pro-British Sultan Hamad bin Thuwaini died and his cousin, Khalid bin Barghash, seized power without British approval. The British Empire issued an ultimatum for him to abdicate, which was ignored. In response, the Royal Navy commenced a bombardment of the Sultan's palace at 9:02 AM. By 9:40 AM, the palace was destroyed and the Sultan's flag was lowered, marking a swift and decisive victory for the British and ending the conflict in under 40 minutes." },
          { "title": "A Single Bolt of Lightning Contains Immense Energy", "text": "A bolt of lightning is a spectacular display of nature's power, releasing an immense amount of energy in a fraction of a second. It can reach temperatures hotter than the surface of the sun and carry up to one billion volts of electricity. While the total energy—around 5 billion joules—is theoretically enough for mundane tasks like toasting bread on a massive scale, harnessing it is practically impossible. The energy is delivered in an incredibly short, unpredictable burst, making its capture and storage beyond the reach of current technology. This fact highlights the sheer scale of energy present in natural atmospheric phenomena." }
        ],
        "whoWereThey": [
          { "name": "Steve Jobs", "bio": "Co-founder and CEO of Apple Inc., a visionary who revolutionized the personal computer, music, and mobile industries." },
          { "name": "Nelson Mandela", "bio": "A South African anti-apartheid revolutionary and political leader who served as the first president of South Africa from 1994 to 1999." },
          { "name": "Eleanor Roosevelt", "bio": "An American political figure, diplomat, and activist. She served as the First Lady of the United States and was a tireless advocate for human rights." }
        ]
      },
      "he": {
        "quoteOfTheDay": [
          "הדרך היחידה לעשות עבודה נהדרת היא לאהוב את מה שאתה עושה. – סטיב ג'ובס",
          "התהילה הגדולה ביותר בחיים אינה טמונה בכך שלעולם לא ניפול, אלא בכך שנקום בכל פעם שאנו נופלים. – נלסון מנדלה",
          "העתיד שייך לאלה המאמינים ביופיים של חלומותיהם. – אלינור רוזוולט"
        ],
        "interestingKnowledge": [
          { "title": "מגדל אייפל יכול 'לצמוח' בקיץ", "text": "מגדל אייפל, שנבנה מברזל מחושל, מהווה דוגמה יוצאת דופן להנדסה של המאה ה-19. החומר ממנו הוא עשוי מעניק לו תכונה מפתיעה: גובהו משתנה עם עונות השנה. תופעה זו, המכונה התפשטות תרמית, גורמת לברזל להתרחב בחום ולהתכווץ בקור. ביום קיץ חם בפריז, התרחבות זו יכולה לגרום לפסגת המגדל לעלות בכ-15 סנטימטרים (כ-6 אינץ') בהשוואה לגובהו בחורף. גוסטב אייפל התחשב בכך בצורה גאונית, ושילב מחברי התפשטות המאפשרים למבנה להתגמש מבלי להינזק." },
          { "title": "לתמנונים יש שלושה לבבות ודם כחול", "text": "לתמנון מערכת דם מרתקת ויעילה ביותר. שניים משלושת לבבותיו מוקדשים להזרמת דם דרך הזימים, שם הוא קולט חמצן, בעוד הלב השלישי והגדול יותר מזרים את הדם המחומצן לשאר הגוף. דמם כחול בשל נוכחותו של המוציאנין, חלבון מבוסס נחושת, שיעיל יותר בהובלת חמצן בסביבות קרות ודלות חמצן בהשוואה להמוגלובין מבוסס הברזל המצוי בדם אנושי. ביולוגיה ייחודית זו היא סיבה מרכזית להישרדותם במערכות אקולוגיות ימיות מגוונות." },
          { "title": "דבש לעולם אינו מתקלקל", "text": "אורך החיים המדהים של הדבש נובע מהתכונות הכימיות הייחודיות שלו. תכולת המים הנמוכה ביותר שלו יוצרת סביבה יבשה מדי עבור חיידקים ומיקרואורגניזמים. בנוסף, הדבש חומצי מאוד, עם רמת pH שמקשה על רוב החיידקים לשרוד. אך ההגנה המרתקת ביותר שלו היא אנזים בשם גלוקוז אוקסידאז, שנוסף על ידי הדבורים. כאשר הדבש נחשף ללחות, אנזים זה מייצר כמויות קטנות של מי חמצן, חומר אנטי-מיקרוביאלי חזק. מערכת שימור טבעית זו כה יעילה, עד שארכיאולוגים גילו דבש אכיל בקברים מצריים עתיקים בני למעלה מ-3,000 שנה." },
          { "title": "המלחמה הקצרה בהיסטוריה נמשכה 38 דקות", "text": "מלחמת אנגליה-זנזיבר מחזיקה בשיא המלחמה הקצרה ביותר בהיסטוריה המתועדת, והיא התרחשה ב-27 באוגוסט 1896. הסכסוך פרץ לאחר שהסולטן הפרו-בריטי חמד בן ת'וואיני מת ובן דודו, ח'אלד בן ברע'ש, תפס את השלטון ללא אישור בריטי. האימפריה הבריטית הציבה לו אולטימטום לפרוש, אך הוא התעלם ממנו. בתגובה, הצי המלכותי החל בהפצצת ארמון הסולטן בשעה 9:02 בבוקר. עד 9:40, הארמון נהרס ודגל הסולטן הורד, מה שסימן ניצחון מהיר והחלטי לבריטים וסיים את הסכסוך בפחות מ-40 דקות." },
          { "title": "במכת ברק יש אנרגיה עצומה", "text": "מכת ברק היא תצוגה מרהיבה של כוח הטבע, המשחררת כמות עצומה של אנרגיה בשבריר שנייה. היא יכולה להגיע לטמפרטורות גבוהות יותר מפני השמש ולשאת עד מיליארד וולט של חשמל. בעוד שהאנרגיה הכוללת - כ-5 מיליארד ג'אול - מספיקה תיאורטית למשימות כמו קליית לחם בקנה מידה עצום, ניצולה כמעט בלתי אפשרי. האנרגיה מועברת בפרץ קצר ובלתי צפוי, מה שהופך את לכידתה ואחסונה למעבר ליכולות הטכנולוגיה הנוכחית. עובדה זו מדגישה את סדר הגודל העצום של האנרגיה בתופעות אטמוספריות טבעיות." }
        ],
        "whoWereThey": [
          { "name": "סטיב ג'ובס", "bio": "מייסד שותף ומנכ\"ל אפל, איש חזון שחולל מהפכה בתעשיות המחשב האישי, המוזיקה והמובייל." },
          { "name": "נלסון מנדלה", "bio": "מהפכן ופעיל נגד האפרטהייד בדרום אפריקה, שכיהן כנשיא הראשון של דרום אפריקה בין השנים 1994 ל-1999." },
          { "name": "אלינור רוזוולט", "bio": "דמות פוליטית, דיפלומטית ופעילה אמריקאית. היא כיהנה כגברת הראשונה של ארה\"ב והייתה תומכת בלתי נלאית בזכויות אדם." }
        ]
      },
      "es": {
        "quoteOfTheDay": [
            "La única manera de hacer un gran trabajo es amar lo que haces. – Steve Jobs",
            "La mayor gloria de vivir no reside en no caer nunca, sino en levantarnos cada vez que caemos. – Nelson Mandela",
            "El futuro pertenece a quienes creen en la belleza de sus sueños. – Eleanor Roosevelt"
        ],
        "interestingKnowledge": [
            { "title": "La Torre Eiffel puede 'crecer' en verano", "text": "Construida con hierro forjado, la Torre Eiffel es un ejemplo notable de la ingeniería del siglo XIX. Su propio material le confiere una característica sorprendente: cambia de altura con las estaciones. Este fenómeno, conocido como expansión térmica, hace que el hierro se expanda al calentarse. En un caluroso día de verano en París, esta expansión puede hacer que la cima de la torre se eleve hasta 15 centímetros en comparación con su altura en invierno. Gustave Eiffel lo tuvo en cuenta, incorporando juntas de expansión que permiten que la estructura se flexione sin sufrir daños." },
            { "title": "Los pulpos tienen tres corazones y sangre azul", "text": "El pulpo posee un sistema circulatorio fascinante y muy eficiente. Dos de sus tres corazones se dedican a bombear sangre a través de las branquias, donde recoge oxígeno, mientras que el tercer corazón, más grande, la distribuye al resto del cuerpo. Su sangre es azul debido a la presencia de hemocianina, una proteína a base de cobre, más eficiente para transportar oxígeno en ambientes fríos y con poco oxígeno que la hemoglobina a base de hierro. Esta biología única es una razón clave para su supervivencia en diversos ecosistemas marinos." },
            { "title": "La miel nunca se estropea", "text": "La notable longevidad de la miel es resultado de sus propiedades químicas. Su bajísimo contenido de agua crea un ambiente demasiado árido para que sobrevivan bacterias. Además, la miel es muy ácida, con un pH inhóspito para la mayoría de los microbios. Pero su defensa más fascinante es una enzima llamada glucosa oxidasa, añadida por las abejas. Cuando la miel se expone a la humedad, esta enzima produce pequeñas cantidades de peróxido de hidrógeno, un potente agente antimicrobiano. Este sistema conservante natural es tan eficaz que se ha encontrado miel comestible en tumbas egipcias de más de 3.000 años." },
            { "title": "La guerra más corta de la historia duró 38 minutos", "text": "La Guerra Anglo-Zanzibariana ostenta el récord de la guerra más corta de la historia, librada el 27 de agosto de 1896. El conflicto estalló después de que el sultán pro-británico muriera y su primo tomara el poder sin la aprobación británica. El Imperio Británico le dio un ultimátum para que abdicara, que fue ignorado. En respuesta, la Royal Navy bombardeó el palacio del Sultán a las 9:02 AM. A las 9:40 AM, el palacio fue destruido y la bandera del Sultán fue arriada, marcando una victoria rápida y decisiva para los británicos." },
            { "title": "Un solo rayo contiene una energía inmensa", "text": "Un rayo es una demostración del poder de la naturaleza, que libera una inmensa cantidad de energía. Puede alcanzar temperaturas más altas que la superficie del sol y transportar hasta mil millones de voltios. Aunque la energía total —unos 5 mil millones de julios— es teóricamente suficiente para tareas mundanas a gran escala, aprovecharla es prácticamente imposible. La energía se libera en una ráfaga corta e impredecible, lo que hace que su captura y almacenamiento estén fuera del alcance de la tecnología actual. Este hecho resalta la enorme escala de energía en los fenómenos atmosféricos." }
        ],
        "whoWereThey": [
            { "name": "Steve Jobs", "bio": "Cofundador y director ejecutivo de Apple Inc., un visionario que revolucionó las industrias de la computación personal, la música y la telefonía móvil." },
            { "name": "Nelson Mandela", "bio": "Revolucionario anti-apartheid y líder político sudafricano que fue el primer presidente de Sudáfrica de 1994 a 1999." },
            { "name": "Eleanor Roosevelt", "bio": "Figura política, diplomática y activista estadounidense. Sirvió como Primera Dama de los EE. UU. y fue una incansable defensora de los derechos humanos." }
        ]
      },
      "fr": {
        "quoteOfTheDay": [
            "La seule façon de faire du bon travail, c'est d'aimer ce que vous faites. – Steve Jobs",
            "La plus grande gloire n'est pas de ne jamais tomber, mais de se relever à chaque chute. – Nelson Mandela",
            "L'avenir appartient à ceux qui croient en la beauté de leurs rêves. – Eleanor Roosevelt"
        ],
        "interestingKnowledge": [
            { "title": "La Tour Eiffel peut 'grandir' en été", "text": "Construite en fer puddlé, la Tour Eiffel est un exemple de l'ingénierie du XIXe siècle. Son matériau lui confère une caractéristique surprenante : sa hauteur change avec les saisons. Ce phénomène, la dilatation thermique, fait que le fer se dilate à la chaleur. Lors d'une chaude journée d'été à Paris, le sommet de la tour peut s'élever jusqu'à 15 centimètres par rapport à sa hauteur en hiver. Gustave Eiffel a ingénieusement prévu cela, en incorporant des joints de dilatation qui permettent à la structure de fléchir sans subir de dommages." },
            { "title": "Les pieuvres ont trois cœurs et du sang bleu", "text": "La pieuvre possède un système circulatoire fascinant. Deux de ses trois cœurs pompent le sang à travers les branchies pour capter l'oxygène, tandis que le troisième, plus grand, le distribue au reste du corps. Leur sang est bleu en raison de l'hémocyanine, une protéine à base de cuivre, plus efficace pour transporter l'oxygène dans des environnements froids et peu oxygénés que l'hémoglobine à base de fer. Cette biologie unique est une raison clé de leur survie dans divers écosystèmes marins." },
            { "title": "Le miel ne se gâte jamais", "text": "La longévité du miel résulte de ses propriétés chimiques. Sa très faible teneur en eau crée un environnement trop aride pour les bactéries. De plus, le miel est très acide, avec un pH inhospitalier pour la plupart des microbes. Mais sa défense la plus fascinante est une enzyme ajoutée par les abeilles, la glucose oxydase. Exposée à l'humidité, cette enzyme produit de petites quantités de peroxyde d'hydrogène, un puissant agent antimicrobien. Ce système de conservation est si efficace que des archéologues ont découvert du miel comestible dans des tombes égyptiennes vieilles de plus de 3 000 ans." },
            { "title": "La guerre la plus courte de l'histoire a duré 38 minutes", "text": "La guerre anglo-zanzibarienne détient le record de la guerre la plus courte, menée le 27 août 1896. Le conflit a éclaté après la mort du sultan pro-britannique et la prise de pouvoir par son cousin sans l'approbation britannique. L'Empire britannique lui a adressé un ultimatum pour qu'il abdique, qui a été ignoré. En réponse, la Royal Navy a bombardé le palais du sultan à 9h02. À 9h40, le palais était détruit et le drapeau du sultan était abaissé, marquant une victoire rapide et décisive pour les Britanniques." },
            { "title": "Un seul éclair contient une énergie immense", "text": "Un éclair est une démonstration de la puissance de la nature, libérant une immense énergie. Il peut atteindre des températures plus élevées que la surface du soleil et transporter jusqu'à un milliard de volts. Bien que l'énergie totale — environ 5 milliards de joules — soit théoriquement suffisante pour des tâches banales à grande échelle, son exploitation est impossible. L'énergie est libérée dans une rafale courte et imprévisible, rendant sa capture et son stockage hors de portée de la technologie actuelle. Ce fait souligne l'échelle de l'énergie dans les phénomènes atmosphériques." }
        ],
        "whoWereThey": [
            { "name": "Steve Jobs", "bio": "Cofondateur et PDG d'Apple Inc., un visionnaire qui a révolutionné l'ordinateur personnel, la musique et les industries mobiles." },
            { "name": "Nelson Mandela", "bio": "Révolutionnaire anti-apartheid et leader politique sud-africain, premier président de l'Afrique du Sud de 1994 à 1999." },
            { "name": "Eleanor Roosevelt", "bio": "Personnalité politique, diplomate et militante américaine. Elle a été Première Dame des États-Unis et une ardente défenseure des droits de l'homme." }
        ]
      },
      "de": {
        "quoteOfTheDay": [
            "Der einzige Weg, großartige Arbeit zu leisten, ist, zu lieben, was man tut. – Steve Jobs",
            "Der größte Ruhm im Leben liegt nicht darin, niemals zu fallen, sondern jedes Mal wieder aufzustehen. – Nelson Mandela",
            "Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben. – Eleanor Roosevelt"
        ],
        "interestingKnowledge": [
            { "title": "Der Eiffelturm kann im Sommer 'wachsen'", "text": "Der aus Schmiedeeisen erbaute Eiffelturm ist ein Beispiel für die Ingenieurskunst des 19. Jahrhunderts. Sein Material verleiht ihm eine überraschende Eigenschaft: Er verändert seine Höhe mit den Jahreszeiten. Dieses Phänomen, die Wärmeausdehnung, bewirkt, dass sich das Eisen bei Erwärmung ausdehnt. An einem heißen Sommertag in Paris kann die Turmspitze dadurch um bis zu 15 Zentimeter höher sein als im Winter. Gustave Eiffel hat dies genial berücksichtigt und Dehnungsfugen eingebaut, die es der Struktur ermöglichen, sich ohne Schaden zu biegen." },
            { "title": "Oktopusse haben drei Herzen und blaues Blut", "text": "Der Oktopus besitzt ein faszinierendes Kreislaufsystem. Zwei seiner drei Herzen pumpen Blut durch die Kiemen, um Sauerstoff aufzunehmen, während das dritte, größere Herz es im Rest des Körpers verteilt. Ihr Blut ist aufgrund von Hämocyanin, einem kupferbasierten Protein, blau. Es transportiert Sauerstoff in kalten, sauerstoffarmen Umgebungen effizienter als das eisenbasierte Hämoglobin. Diese einzigartige Biologie ist ein Schlüssel für ihr Überleben in verschiedenen marinen Ökosystemen." },
            { "title": "Honig verdirbt nie", "text": "Die Langlebigkeit von Honig ist das Ergebnis seiner chemischen Eigenschaften. Sein extrem niedriger Wassergehalt schafft eine zu trockene Umgebung für Bakterien. Zudem ist Honig stark sauer, mit einem für die meisten Mikroben unwirtlichen pH-Wert. Seine faszinierendste Abwehr ist jedoch ein von Bienen hinzugefügtes Enzym namens Glucoseoxidase. Bei Kontakt mit Feuchtigkeit produziert dieses Enzym geringe Mengen Wasserstoffperoxid, ein starkes antimikrobielles Mittel. Dieses System ist so wirksam, dass Archäologen in über 3.000 Jahre alten ägyptischen Gräbern essbaren Honig gefunden haben." },
            { "title": "Der kürzeste Krieg der Geschichte dauerte 38 Minuten", "text": "Der Anglo-Sansibar-Krieg hält den Rekord für den kürzesten Krieg und wurde am 27. August 1896 geführt. Der Konflikt brach aus, nachdem der pro-britische Sultan gestorben war und sein Cousin ohne britische Zustimmung die Macht übernommen hatte. Das Britische Empire stellte ihm ein Ultimatum zur Abdankung, das ignoriert wurde. Daraufhin bombardierte die Royal Navy um 9:02 Uhr den Palast des Sultans. Um 9:40 Uhr war der Palast zerstört und die Flagge des Sultans wurde gesenkt, was einen schnellen Sieg für die Briten bedeutete." },
            { "title": "Ein einzelner Blitz enthält immense Energie", "text": "Ein Blitz ist eine Demonstration der Kraft der Natur, die immense Energie freisetzt. Er kann Temperaturen erreichen, die heißer sind als die Sonnenoberfläche, und bis zu einer Milliarde Volt tragen. Obwohl die Gesamtenergie – etwa 5 Milliarden Joule – theoretisch für alltägliche Aufgaben ausreichen würde, ist ihre Nutzung unmöglich. Die Energie wird in einem kurzen, unvorhersehbaren Stoß abgegeben, was ihre Erfassung und Speicherung für die aktuelle Technologie unerreichbar macht. Dies unterstreicht das Ausmaß der Energie in atmosphärischen Phänomenen." }
        ],
        "whoWereThey": [
            { "name": "Steve Jobs", "bio": "Mitbegründer und CEO von Apple Inc., ein Visionär, der den Personal Computer, die Musik- und Mobilfunkbranche revolutionierte." },
            { "name": "Nelson Mandela", "bio": "Südafrikanischer Anti-Apartheid-Revolutionär und politischer Führer, der von 1994 bis 1999 der erste Präsident Südafrikas war." },
            { "name": "Eleanor Roosevelt", "bio": "Amerikanische Politikerin, Diplomatin und Aktivistin. Sie war First Lady der USA und eine unermüdliche Verfechterin der Menschenrechte." }
        ]
      },
      "tr": {
        "quoteOfTheDay": [
            "Harika bir iş yapmanın tek yolu, yaptığınız işi sevmektir. – Steve Jobs",
            "Yaşamdaki en büyük zafer asla düşmemek değil, her düştüğümüzde yeniden ayağa kalkmaktır. – Nelson Mandela",
            "Gelecek, hayallerinin güzelliğine inananlara aittir. – Eleanor Roosevelt"
        ],
        "interestingKnowledge": [
            { "title": "Eyfel Kulesi Yaz aylarında 'Büyüyebilir'", "text": "Dövme demirden inşa edilen Eyfel Kulesi, 19. yüzyıl mühendisliğinin bir örneğidir. Malzemesi ona şaşırtıcı bir özellik kazandırır: yüksekliği mevsimlere göre değişir. Termal genleşme olarak bilinen bu olay, demirin ısındığında genleşmesine neden olur. Paris'te sıcak bir yaz gününde, kulenin tepesi kışa göre 15 santimetreye kadar yükselebilir. Gustave Eiffel bunu ustaca hesaba katarak, yapının hasar görmeden esnemesine olanak tanıyan genleşme derzleri eklemiştir." },
            { "title": "Ahtapotların Üç Kalbi ve Mavi Kanı Vardır", "text": "Ahtapotun büyüleyici bir dolaşım sistemi vardır. Üç kalbinden ikisi, oksijen aldığı solungaçlara kan pompalar, üçüncüsü ve daha büyüğü ise vücudun geri kalanına dağıtır. Kanları, insan kanındaki demir bazlı hemoglobine kıyasla soğuk, düşük oksijenli ortamlarda oksijeni daha verimli taşıyan bakır bazlı bir protein olan hemosiyanin varlığı nedeniyle mavidir. Bu eşsiz biyoloji, çeşitli deniz ekosistemlerinde hayatta kalmalarının anahtarıdır." },
            { "title": "Bal Asla Bozulmaz", "text": "Balın uzun ömürlü olması, kimyasal özelliklerinden kaynaklanır. Çok düşük su içeriği, bakteriler için fazla kurak bir ortam yaratır. Ayrıca, balın pH'ı çoğu mikrop için elverişsizdir. Ama en büyüleyici savunması, arıların eklediği glukoz oksidaz adlı bir enzimdir. Bal neme maruz kaldığında, bu enzim küçük miktarlarda güçlü bir antimikrobiyal ajan olan hidrojen peroksit üretir. Bu sistem o kadar etkilidir ki, 3000 yıldan eski Mısır mezarlarında yenilebilir bal bulunmuştur." },
            { "title": "Tarihteki en kısa savaş 38 dakika sürdü", "text": "Anglo-Zanzibar Savaşı, 27 Ağustos 1896'da yapılan tarihin en kısa savaşı rekorunu elinde tutuyor. Çatışma, İngiliz yanlısı Sultan'ın ölümü ve kuzeninin İngiliz onayı olmadan iktidarı ele geçirmesinden sonra patlak verdi. Britanya İmparatorluğu ona tahttan çekilmesi için bir ültimatom verdi, ancak bu göz ardı edildi. Buna karşılık, Kraliyet Donanması saat 9:02'de Sultan'ın sarayını bombalamaya başladı. Saat 9:40'ta saray yıkıldı ve bu, İngilizler için hızlı ve kesin bir zafer anlamına geliyordu." },
            { "title": "Tek bir şimşek muazzam enerji içerir", "text": "Bir şimşek, doğanın gücünün bir göstergesidir ve muazzam enerji açığa çıkarır. Güneş yüzeyinden daha yüksek sıcaklıklara ulaşabilir ve bir milyar volta kadar taşıyabilir. Toplam enerji – yaklaşık 5 milyar jul – teorik olarak sıradan işler için yeterli olsa da, bundan faydalanmak imkansızdır. Enerji, kısa ve öngörülemez bir patlama ile salınır, bu da yakalanmasını ve depolanmasını mevcut teknolojinin ötesine taşır. Bu, atmosferik olaylardaki enerjinin ölçeğini vurgular." }
        ],
        "whoWereThey": [
            { "name": "Steve Jobs", "bio": "Apple Inc.'in kurucu ortağı ve CEO'su, kişisel bilgisayar, müzik ve mobil endüstrilerinde devrim yaratan bir vizyoner." },
            { "name": "Nelson Mandela", "bio": "1994'ten 1999'a kadar Güney Afrika'nın ilk cumhurbaşkanı olarak görev yapan Güney Afrikalı bir anti-apartheid devrimcisi ve siyasi lider." },
            { "name": "Eleanor Roosevelt", "bio": "Amerikalı bir siyasi figür, diplomat ve aktivist. ABD'nin First Lady'si olarak görev yaptı ve yorulmak bilmez bir insan hakları savunucusuydu." }
        ]
      }
    }
  },
  // DAY 2
  {
    languages: {
      "en": {
        "quoteOfTheDay": [
          "If you can't explain it simply, you don't understand it well enough. – Albert Einstein",
          "Try to be a rainbow in someone's cloud. – Maya Angelou",
          "Simplicity is the ultimate sophistication. – Leonardo da Vinci"
        ],
        "interestingKnowledge": [
          { "title": "A Day on Venus is Longer than its Year", "text": "Venus presents a fascinating paradox: its rotational period is longer than its orbital period. It takes a sluggish 243 Earth days for Venus to complete a single rotation on its axis, but only 225 Earth days to orbit the Sun. This means a Venusian day is longer than a Venusian year. This is attributed to its retrograde (backward) rotation and its incredibly thick, fast-moving atmosphere, which may create a tidal drag on the planet's surface, slowing its spin over billions of years." },
          { "title": "There Are More Trees on Earth Than Stars in the Milky Way", "text": "While the night sky appears filled with countless stars, the number of trees on our own planet is estimated to be vastly greater. A study published in the journal 'Nature' estimated there are over 3 trillion trees on Earth. In contrast, astronomers estimate that the Milky Way galaxy contains between 100 to 400 billion stars. This surprising fact underscores the immense scale of Earth's biosphere and the critical role forests play in sustaining life. It serves as a powerful reminder of the precious and vast natural resources our planet holds." },
          { "title": "Wombats Have Cube-Shaped Poop", "text": "The wombat, a marsupial native to Australia, is unique in the animal kingdom for producing cube-shaped feces. This bizarre trait is a result of the varying elasticity of its intestinal walls. As digested food moves through the final sections of the intestine, the alternating soft and rigid regions sculpt the waste into distinct cubes. This shape is not just a quirk; it serves a practical purpose. Wombats use their droppings to mark territory, and the flat sides of the cubes prevent them from rolling away from prominent locations like logs or rocks." },
          { "title": "Sharks Are Older Than Trees", "text": "Sharks are true survivors of the ancient world, having navigated Earth's oceans for approximately 450 million years. This makes them one of the oldest animal groups still in existence, predating even the dinosaurs. In contrast, the earliest known trees, such as the fern-like Archaeopteris, only appeared around 350 million years ago. This means that sharks had already been ruling the seas for a staggering 100 million years before the first forests began to spread across the land. Their long evolutionary history is a testament to their remarkable adaptability and resilience through multiple mass extinction events." },
          { "title": "The 'Sound' of a Black Hole", "text": "Although space is a vacuum where sound as we know it cannot travel, black holes are not silent. In 2003, NASA's Chandra X-ray Observatory detected pressure waves rippling through the hot gas in the Perseus galaxy cluster, generated by a supermassive black hole at its center. These waves are essentially sound waves with a very low frequency. Scientists were able to translate these ripples into a note, albeit one that is 57 octaves below middle C, making it far too deep for the human ear to perceive. This discovery revealed that on a cosmic scale, even the most mysterious objects can create a form of 'music'." }
        ],
        "whoWereThey": [
          { "name": "Albert Einstein", "bio": "A German-born theoretical physicist who developed the theory of relativity. His work is also known for its influence on the philosophy of science." },
          { "name": "Maya Angelou", "bio": "An American poet, memoirist, and civil rights activist. She published seven autobiographies, three books of essays, and several books of poetry." },
          { "name": "Leonardo da Vinci", "bio": "An Italian polymath of the High Renaissance, active as a painter, engineer, scientist, and architect. His genius epitomized the Renaissance humanist ideal." }
        ]
      },
      "he": {
        "quoteOfTheDay": [
          "אם אינך יכול להסביר זאת בפשטות, אינך מבין זאת מספיק טוב. – אלברט איינשטיין",
          "נסה להיות קשת בענן של מישהו. – מאיה אנג'לו",
          "פשטות היא התחכום האולטימטיבי. – לאונרדו דה וינצ'י"
        ],
        "interestingKnowledge": [
          { "title": "יום על נוגה ארוך יותר משנה על נוגה", "text": "נוגה מציג פרדוקס מרתק: תקופת הסיבוב העצמי שלו ארוכה יותר מתקופת ההקפה שלו. לנוגה לוקח 243 ימי ארץ איטיים להשלים סיבוב אחד על צירו, אך רק 225 ימי ארץ להקיף את השמש. משמעות הדבר היא שיממה על נוגה ארוכה יותר משנה על נוגה. מאפיין זה מיוחס לסיבוב הרטרוגרדי (הפוך) שלו ולאטמוספירה העבה והמהירה שלו, שעשויה ליצור גרירת גאות על פני הכוכב, ולהאט את סיבובו במשך מיליארדי שנים." },
          { "title": "יש יותר עצים על כדור הארץ מאשר כוכבים בשביל החלב", "text": "בעוד ששמי הלילה נראים מלאים בכוכבים, מספר העצים על כדור הארץ מוערך כגדול בהרבה. מחקר העריך כי ישנם למעלה מ-3 טריליון עצים. לשם השוואה, אסטרונומים מעריכים כי גלקסיית שביל החלב מכילה בין 100 ל-400 מיליארד כוכבים. עובדה מפתיעה זו מדגישה את קנה המידה העצום של הביוספרה של כדור הארץ ואת התפקיד הקריטי שיערות ממלאים בקיום החיים. זה משמש כתזכורת למשאבי הטבע העצומים שכוכב הלכת שלנו מחזיק." },
          { "title": "לוומבטים יש צואה בצורת קובייה", "text": "הוומבט, חיית כיס ילידת אוסטרליה, הוא ייחודי בממלכת החי בכך שהוא מייצר צואה בצורת קובייה. תכונה מוזרה זו היא תוצאה של הגמישות המשתנה של דפנות המעיים שלו. כאשר מזון מעוכל נע דרך החלקים הסופיים של המעי, האזורים הרכים והקשיחים המתחלפים מעצבים את הפסולת לקוביות. לצורה זו יש מטרה מעשית; וומבטים משתמשים בגללים שלהם לסימון טריטוריה, והצדדים השטוחים של הקוביות מונעים מהם להתגלגל ממקומות בולטים." },
          { "title": "כרישים עתיקים יותר מעצים", "text": "כרישים הם שורדים אמיתיים של העולם העתיק, לאחר שניווטו באוקיינוסים של כדור הארץ במשך כ-450 מיליון שנה. זה הופך אותם לאחת מקבוצות בעלי החיים העתיקות ביותר שעדיין קיימות, והם קדמו אפילו לדינוזאורים. לשם השוואה, העצים המוקדמים ביותר הידועים הופיעו רק לפני כ-350 מיליון שנה. משמעות הדבר היא שכרישים כבר שלטו בימים במשך 100 מיליון שנים מדהימות לפני שהיערות הראשונים החלו להתפשט על פני היבשה. ההיסטוריה האבולוציונית הארוכה שלהם היא עדות לחוסן המדהים שלהם." },
          { "title": "ה'צליל' של חור שחור", "text": "אף שהחלל הוא ואקום שבו קול כפי שאנו מכירים אותו אינו יכול להתפשט, חורים שחורים אינם שקטים. בשנת 2003, מצפה הכוכבים Chandra של נאס\"א זיהה גלי לחץ המתפשטים בגז החם בצביר הגלקסיות פרסאוס, הנוצרים על ידי חור שחור על-מסיבי במרכזו. גלים אלה הם למעשה גלי קול בתדירות נמוכה מאוד. מדענים הצליחו לתרגם את האדוות הללו לתו, אם כי הוא נמוך ב-57 אוקטבות מהדו האמצעי, מה שהופך אותו לעמוק מדי מכדי שאוזן אנושית תוכל לקלוט. תגלית זו חשפה כי בקנה מידה קוסמי, אפילו האובייקטים המסתוריים ביותר יכולים ליצור סוג של 'מוזיקה'." }
        ],
        "whoWereThey": [
          { "name": "אלברט איינשטיין", "bio": "פיזיקאי תיאורטי יליד גרמניה שפיתח את תורת היחסות. עבודתו ידועה גם בהשפעתה על הפילוסופיה של המדע." },
          { "name": "מאיה אנג'לו", "bio": "משוררת, סופרת זיכרונות ופעילת זכויות אזרח אמריקאית. היא פרסמה שבע אוטוביוגרפיות, שלושה ספרי מאמרים ומספר ספרי שירה." },
          { "name": "לאונרדו דה וינצ'י", "bio": "איש אשכולות איטלקי מתקופת הרנסאנס, פעיל כצייר, מהנדס, מדען ואדריכל. גאונותו גילמה את האידיאל ההומניסטי של הרנסאנס." }
        ]
      },
      "es": {
          "quoteOfTheDay": [
              "Si no puedes explicarlo de forma sencilla, no lo entiendes lo suficientemente bien. – Albert Einstein",
              "Intenta ser un arcoíris en la nube de alguien. – Maya Angelou",
              "La simplicidad es la máxima sofisticación. – Leonardo da Vinci"
          ],
          "interestingKnowledge": [
              { "title": "Un día en Venus es más largo que su año", "text": "Venus presenta una paradoja fascinante: su período de rotación es más largo que su período orbital. A Venus le toma 243 días terrestres completar una sola rotación, pero solo 225 días terrestres para orbitar el Sol. Esto significa que un día venusiano es más largo que un año venusiano. Esto se atribuye a su rotación retrógrada (hacia atrás) y a su atmósfera increíblemente densa y de rápido movimiento, que puede crear un arrastre de marea en la superficie del planeta, ralentizando su giro." },
              { "title": "Hay más árboles en la Tierra que estrellas en la Vía Láctea", "text": "Aunque el cielo nocturno parece lleno de innumerables estrellas, se estima que el número de árboles en nuestro planeta es mucho mayor. Un estudio estimó que hay más de 3 billones de árboles en la Tierra. En contraste, los astrónomos estiman que la Vía Láctea contiene entre 100 y 400 mil millones de estrellas. Este hecho sorprendente subraya la inmensa escala de la biosfera de la Tierra y el papel fundamental que desempeñan los bosques en el sostenimiento de la vida. Sirve como un poderoso recordatorio de los vastos recursos naturales de nuestro planeta." },
              { "title": "Los wombats tienen excrementos en forma de cubo", "text": "El wombat, un marsupial nativo de Australia, es único en el reino animal por producir heces en forma de cubo. Este rasgo extraño es el resultado de la elasticidad variable de sus paredes intestinales. A medida que el alimento digerido se mueve a través de las secciones finales del intestino, las regiones alternas blandas y rígidas esculpen los desechos en cubos. Esta forma tiene un propósito práctico: los wombats usan sus excrementos para marcar territorio, y los lados planos de los cubos evitan que rueden lejos de lugares prominentes." },
              { "title": "Los tiburones son más antiguos que los árboles", "text": "Los tiburones son verdaderos supervivientes del mundo antiguo, habiendo navegado por los océanos de la Tierra durante aproximadamente 450 millones de años. Esto los convierte en uno de los grupos de animales más antiguos que aún existen, anteriores incluso a los dinosaurios. En contraste, los primeros árboles conocidos aparecieron hace solo unos 350 millones de años. Esto significa que los tiburones ya habían estado dominando los mares durante 100 millones de años antes de que los primeros bosques comenzaran a extenderse por la tierra. Su larga historia evolutiva es un testimonio de su notable capacidad de adaptación." },
              { "title": "El 'sonido' de un agujero negro", "text": "Aunque el espacio es un vacío donde el sonido no puede viajar, los agujeros negros no son silenciosos. En 2003, el Observatorio de rayos X Chandra de la NASA detectó ondas de presión en el gas caliente del cúmulo de galaxias de Perseo, generadas por un agujero negro supermasivo en su centro. Estas ondas son esencialmente ondas sonoras de muy baja frecuencia. Los científicos pudieron traducir estas ondas en una nota, aunque una que está 57 octavas por debajo del do central, lo que la hace demasiado profunda para que el oído humano la perciba. Este descubrimiento reveló que, a escala cósmica, incluso los objetos más misteriosos pueden crear una forma de 'música'." }
          ],
          "whoWereThey": [
              { "name": "Albert Einstein", "bio": "Un físico teórico nacido en Alemania que desarrolló la teoría de la relatividad. Su trabajo también es conocido por su influencia en la filosofía de la ciencia." },
              { "name": "Maya Angelou", "bio": "Poeta, memorialista y activista de derechos civiles estadounidense. Publicó siete autobiografías, tres libros de ensayos y varios libros de poesía." },
              { "name": "Leonardo da Vinci", "bio": "Un polímata italiano del Alto Renacimiento, activo como pintor, ingeniero, científico y arquitecto. Su genio personificó el ideal humanista del Renacimiento." }
          ]
      },
      "fr": {
          "quoteOfTheDay": [
              "Si vous ne pouvez pas l'expliquer simplement, vous ne le comprenez pas assez bien. – Albert Einstein",
              "Essayez d'être un arc-en-ciel dans le nuage de quelqu'un. – Maya Angelou",
              "La simplicité est la sophistication suprême. – Leonardo da Vinci"
          ],
          "interestingKnowledge": [
              { "title": "Un jour sur Vénus est plus long que son année", "text": "Vénus présente un paradoxe fascinant : sa période de rotation est plus longue que sa période orbitale. Il faut 243 jours terrestres à Vénus pour effectuer une seule rotation, mais seulement 225 jours terrestres pour orbiter autour du Soleil. Cela signifie qu'un jour vénusien est plus long qu'une année vénusienne. Ceci est attribué à sa rotation rétrograde (vers l'arrière) et à son atmosphère incroyablement épaisse et rapide, qui peut créer une traînée de marée sur la surface de la planète, ralentissant sa rotation." },
              { "title": "Il y a plus d'arbres sur Terre que d'étoiles dans la Voie lactée", "text": "Alors que le ciel nocturne semble rempli d'étoiles, le nombre d'arbres sur notre planète est estimé être bien plus grand. Une étude a estimé qu'il y a plus de 3 billions d'arbres sur Terre. En revanche, les astronomes estiment que la Voie lactée contient entre 100 et 400 milliards d'étoiles. Ce fait surprenant souligne l'immense échelle de la biosphère terrestre et le rôle essentiel des forêts dans le maintien de la vie. C'est un rappel puissant des vastes ressources naturelles de notre planète." },
              { "title": "Les wombats ont des excréments en forme de cube", "text": "Le wombat, un marsupial originaire d'Australie, est unique dans le règne animal pour produire des excréments en forme de cube. Ce trait bizarre résulte de l'élasticité variable de ses parois intestinales. Au fur et à mesure que les aliments digérés se déplacent dans les dernières sections de l'intestin, les régions alternées molles et rigides sculptent les déchets en cubes. Cette forme a un but pratique : les wombats utilisent leurs excréments pour marquer leur territoire, et les côtés plats des cubes les empêchent de rouler loin des endroits bien en vue." },
              { "title": "Les requins sont plus anciens que les arbres", "text": "Les requins sont de véritables survivants du monde antique, ayant navigué dans les océans de la Terre depuis environ 450 millions d'années. Cela en fait l'un des plus anciens groupes d'animaux encore existants, antérieur même aux dinosaures. En revanche, les premiers arbres connus sont apparus il y a seulement environ 350 millions d'années. Cela signifie que les requins régnaient déjà sur les mers depuis 100 millions d'années avant que les premières forêts ne commencent à se répandre sur la terre. Leur longue histoire évolutive témoigne de leur remarquable capacité d'adaptation." },
              { "title": "Le 'son' d'un trou noir", "text": "Bien que l'espace soit un vide où le son ne peut pas se propager, les trous noirs ne sont pas silencieux. En 2003, l'Observatoire de rayons X Chandra de la NASA a détecté des ondes de pression dans le gaz chaud de l'amas de galaxies de Persée, générées par un trou noir supermassif en son centre. Ces ondes sont essentiellement des ondes sonores de très basse fréquence. Les scientifiques ont pu traduire ces ondes en une note, bien qu'elle soit 57 octaves en dessous du do central, la rendant trop grave pour que l'oreille humaine la perçoive. Cette découverte a révélé qu'à l'échelle cosmique, même les objets les plus mystérieux peuvent créer une forme de 'musique'." }
          ],
          "whoWereThey": [
              { "name": "Albert Einstein", "bio": "Un physicien théoricien d'origine allemande qui a développé la théorie de la relativité. Son travail est également connu pour son influence sur la philosophie des sciences." },
              { "name": "Maya Angelou", "bio": "Poétesse, mémorialiste et militante américaine des droits civiques. Elle a publié sept autobiographies, trois livres d'essais et plusieurs recueils de poésie." },
              { "name": "Leonardo da Vinci", "bio": "Un polymathe italien de la Haute Renaissance, actif en tant que peintre, ingénieur, scientifique et architecte. Son génie incarnait l'idéal humaniste de la Renaissance." }
          ]
      },
      "de": {
          "quoteOfTheDay": [
              "Wenn man es nicht einfach erklären kann, versteht man es nicht gut genug. – Albert Einstein",
              "Versuche, ein Regenbogen in jemandes Wolke zu sein. – Maya Angelou",
              "Einfachheit ist die höchste Form der Raffinesse. – Leonardo da Vinci"
          ],
          "interestingKnowledge": [
              { "title": "Ein Tag auf der Venus ist länger als ihr Jahr", "text": "Die Venus stellt ein faszinierendes Paradoxon dar: Ihre Rotationsperiode ist länger als ihre Umlaufzeit. Die Venus benötigt 243 Erdentage für eine einzige Umdrehung, aber nur 225 Erdentage, um die Sonne zu umkreisen. Das bedeutet, ein Venus-Tag ist länger als ein Venus-Jahr. Dies wird auf ihre retrograde (rückläufige) Rotation und ihre unglaublich dichte, sich schnell bewegende Atmosphäre zurückgeführt, die eine Gezeitenbremse auf die Planetenoberfläche ausüben und ihre Drehung verlangsamen könnte." },
              { "title": "Es gibt mehr Bäume auf der Erde als Sterne in der Milchstraße", "text": "Während der Nachthimmel mit unzähligen Sternen gefüllt zu sein scheint, ist die Anzahl der Bäume auf unserem Planeten schätzungsweise weitaus größer. Eine Studie schätzte, dass es über 3 Billionen Bäume auf der Erde gibt. Im Gegensatz dazu schätzen Astronomen, dass die Milchstraße zwischen 100 und 400 Milliarden Sterne enthält. Diese überraschende Tatsache unterstreicht das immense Ausmaß der Biosphäre der Erde und die entscheidende Rolle der Wälder für das Leben. Sie dient als eindringliche Erinnerung an die riesigen natürlichen Ressourcen unseres Planeten." },
              { "title": "Wombats haben würfelförmigen Kot", "text": "Der Wombat, ein in Australien beheimatetes Beuteltier, ist im Tierreich einzigartig, weil er würfelförmige Fäkalien produziert. Diese bizarre Eigenschaft ist das Ergebnis der unterschiedlichen Elastizität seiner Darmwände. Wenn sich verdaute Nahrung durch die letzten Abschnitte des Darms bewegt, formen die abwechselnd weichen und starren Regionen den Abfall zu Würfeln. Diese Form hat einen praktischen Zweck: Wombats benutzen ihren Kot, um ihr Revier zu markieren, und die flachen Seiten der Würfel verhindern, dass sie von prominenten Stellen wegrollen." },
              { "title": "Haie sind älter als Bäume", "text": "Haie sind wahre Überlebenskünstler der antiken Welt und navigieren seit etwa 450 Millionen Jahren durch die Ozeane der Erde. Damit gehören sie zu den ältesten noch existierenden Tiergruppen und sind sogar älter als die Dinosaurier. Im Gegensatz dazu erschienen die frühesten bekannten Bäume erst vor etwa 350 Millionen Jahren. Das bedeutet, dass Haie die Meere bereits seit 100 Millionen Jahren beherrschten, bevor sich die ersten Wälder auf dem Land ausbreiteten. Ihre lange Evolutionsgeschichte ist ein Beweis für ihre bemerkenswerte Anpassungsfähigkeit." },
              { "title": "Der 'Klang' eines Schwarzen Lochs", "text": "Obwohl der Weltraum ein Vakuum ist, in dem sich Schall nicht ausbreiten kann, sind Schwarze Löcher nicht still. 2003 entdeckte das Chandra-Röntgenobservatorium der NASA Druckwellen im heißen Gas des Perseus-Galaxienhaufens, die von einem supermassiven Schwarzen Loch in seinem Zentrum erzeugt wurden. Diese Wellen sind im Wesentlichen Schallwellen mit sehr niedriger Frequenz. Wissenschaftler konnten diese Wellen in einen Ton umwandeln, der jedoch 57 Oktaven unter dem mittleren C liegt und somit für das menschliche Ohr viel zu tief ist. Diese Entdeckung zeigte, dass auf kosmischer Ebene selbst die mysteriösesten Objekte eine Form von 'Musik' erzeugen können." }
          ],
          "whoWereThey": [
              { "name": "Albert Einstein", "bio": "Ein in Deutschland geborener theoretischer Physiker, der die Relativitätstheorie entwickelte. Sein Werk ist auch für seinen Einfluss auf die Wissenschaftsphilosophie bekannt." },
              { "name": "Maya Angelou", "bio": "Eine amerikanische Dichterin, Memoirenschreiberin und Bürgerrechtlerin. Sie veröffentlichte sieben Autobiografien, drei Essaybände und mehrere Gedichtbände." },
              { "name": "Leonardo da Vinci", "bio": "Ein italienischer Universalgelehrter der Hochrenaissance, tätig als Maler, Ingenieur, Wissenschaftler und Architekt. Sein Genie verkörperte das humanistische Ideal der Renaissance." }
          ]
      },
      "tr": {
          "quoteOfTheDay": [
              "Basitçe açıklayamıyorsan, yeterince iyi anlamamışsın demektir. – Albert Einstein",
              "Birinin bulutunda gökkuşağı olmaya çalış. – Maya Angelou",
              "Basitlik, en üst düzeyde gelişmişliktir. – Leonardo da Vinci"
          ],
          "interestingKnowledge": [
              { "title": "Venüs'te bir gün, bir yıldan daha uzundur", "text": "Venüs büyüleyici bir paradoks sunar: dönüş süresi yörünge süresinden daha uzundur. Venüs'ün tek bir dönüşü tamamlaması 243 Dünya günü sürer, ancak Güneş'in etrafında dönmesi sadece 225 Dünya günü sürer. Bu, bir Venüs gününün bir Venüs yılından daha uzun olduğu anlamına gelir. Bu, geriye doğru dönüşüne ve gezegenin yüzeyinde gelgit sürüklenmesi yaratarak dönüşünü yavaşlatabilen inanılmaz derecede kalın, hızlı hareket eden atmosferine atfedilir." },
              { "title": "Dünya'da Samanyolu'ndaki yıldızlardan daha fazla ağaç var", "text": "Gece gökyüzü sayısız yıldızla dolu görünse de, gezegenimizdeki ağaç sayısının çok daha fazla olduğu tahmin ediliyor. Bir çalışma, Dünya'da 3 trilyondan fazla ağaç olduğunu tahmin etti. Buna karşılık, gökbilimciler Samanyolu galaksisinin 100 ila 400 milyar yıldız içerdiğini tahmin ediyor. Bu şaşırtıcı gerçek, Dünya'nın biyosferinin muazzam ölçeğini ve ormanların yaşamı sürdürmedeki kritik rolünü vurgulamaktadır. Gezegenimizin sahip olduğu değerli ve engin doğal kaynakların güçlü bir hatırlatıcısı olarak hizmet eder." },
              { "title": "Wombatların küp şeklinde kakası vardır", "text": "Avustralya'ya özgü bir keseli olan vombat, küp şeklinde dışkı üretmesiyle hayvanlar aleminde benzersizdir. Bu tuhaf özellik, bağırsak duvarlarının değişen esnekliğinin bir sonucudur. Sindirilmiş yiyecekler bağırsağın son bölümlerinden geçerken, değişen yumuşak ve sert bölgeler atığı küpler halinde şekillendirir. Bu şeklin pratik bir amacı vardır: vombatlar bölgelerini işaretlemek için dışkılarını kullanırlar ve küplerin düz kenarları, belirgin yerlerden yuvarlanmalarını önler." },
              { "title": "Köpekbalıkları ağaçlardan daha yaşlıdır", "text": "Köpekbalıkları, yaklaşık 450 milyon yıldır Dünya okyanuslarında gezinen antik dünyanın gerçek kurtulanlarıdır. Bu onları dinozorlardan bile önce gelen, hala var olan en eski hayvan gruplarından biri yapar. Buna karşılık, bilinen en eski ağaçlar sadece yaklaşık 350 milyon yıl önce ortaya çıktı. Bu, ilk ormanlar karaya yayılmaya başlamadan önce köpekbalıklarının 100 milyon yıldır denizlere hükmettiği anlamına gelir. Uzun evrimsel tarihleri, onların dikkat çekici adaptasyon yeteneklerinin bir kanıtıdır." },
              { "title": "Bir kara deliğin 'sesi'", "text": "Uzay, sesin bildiğimiz gibi yayılamadığı bir boşluk olsa da, kara delikler sessiz değildir. 2003 yılında NASA'nın Chandra X-ışını Gözlemevi, merkezindeki süper kütleli bir kara delik tarafından oluşturulan Perseus galaksi kümesindeki sıcak gazda dalgalanan basınç dalgalarını tespit etti. Bu dalgalar esasen çok düşük frekanslı ses dalgalarıdır. Bilim adamları bu dalgalanmaları bir nota çevirebildiler, ancak bu nota orta C'nin 57 oktav altında olduğu için insan kulağının algılayamayacağı kadar derindir. Bu keşif, kozmik ölçekte en gizemli nesnelerin bile bir tür 'müzik' yaratabildiğini ortaya çıkardı." }
          ],
          "whoWereThey": [
              { "name": "Albert Einstein", "bio": "Görelilik teorisini geliştiren Almanya doğumlu bir teorik fizikçi. Çalışmaları bilim felsefesi üzerindeki etkisiyle de bilinir." },
              { "name": "Maya Angelou", "bio": "Amerikalı bir şair, anı yazarı ve sivil haklar aktivisti. Yedi otobiyografi, üç deneme kitabı ve birkaç şiir kitabı yayınladı." },
              { "name": "Leonardo da Vinci", "bio": "Yüksek Rönesans'ın İtalyan bir polimatı, ressam, mühendis, bilim adamı ve mimar olarak aktifti. Dehası, Rönesans hümanist idealini özetliyordu." }
          ]
      }
    }
  },
  // DAY 3
  {
    languages: {
      "en": {
        "quoteOfTheDay": [
          "Nothing is impossible, the word itself says 'I'm possible'! – Audrey Hepburn",
          "The only thing we have to fear is fear itself. – Franklin D. Roosevelt",
          "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson"
        ],
        "interestingKnowledge": [
          { "title": "The Hawaiian Alphabet Has Only 12 Letters", "text": "The traditional Hawaiian alphabet, or 'ka pīʻāpā Hawaiʻi,' is one of the shortest alphabets in the world, consisting of just five vowels (A, E, I, O, U) and seven consonants (H, K, L, M, N, P, W). Every word in Hawaiian ends in a vowel, and syllables are simple, which gives the language its melodic and flowing sound. This streamlined system makes the language phonetically consistent and relatively easy to pronounce once the basic rules are understood, reflecting a culture that values clarity and harmony in communication." },
          { "title": "A Group of Flamingos is Called a 'Flamboyance'", "text": "This colorful and fitting term perfectly captures the essence of these vibrant, social birds, often seen wading together in large, dazzling groups. The English language is rich with such poetic collective nouns for animals, each often reflecting a unique characteristic of the species. For instance, you might encounter a 'crash' of rhinoceroses, a 'parliament' of wise-looking owls, a 'murder' of ominous crows, or an 'ostentation' of peacocks. These terms add a layer of creativity and history to the way we describe the natural world." },
          { "title": "The World's Largest Desert is Antarctica", "text": "While we typically associate deserts with scorching heat and vast sand dunes, the technical definition of a desert is a region that receives very little precipitation. By this measure, the Antarctic Polar Desert is the largest desert on Earth, covering an area of around 14 million square kilometers. It is also the coldest, driest, and highest desert in the world. The frigid air is unable to hold much moisture, resulting in annual precipitation of less than 200mm, which falls almost exclusively as snow, challenging our conventional image of a desert landscape." },
          { "title": "Cleopatra Was Not Egyptian", "text": "Despite being one of the most famous rulers of Egypt, Cleopatra VII was not of Egyptian descent. She was the last active ruler of the Ptolemaic Kingdom, a dynasty founded by a Macedonian Greek general who was a companion of Alexander the Great. While her family lineage was Greek, Cleopatra fully embraced Egyptian culture and was a rare exception in her dynasty for being the first to learn the Egyptian language. This cultural immersion, combined with her political acumen, made her a formidable and beloved leader among her people." },
          { "title": "The Canary Islands Are Named After Dogs, Not Birds", "text": "The name of this popular Spanish archipelago has a surprising origin that has nothing to do with the cheerful yellow songbird. The islands' name is derived from the Latin phrase 'Canariae Insulae,' which translates to 'Islands of the Dogs.' This name was reportedly given by early explorers who encountered a species of large, fierce dogs ('canes' in Latin) on the islands. It was only later that the small finch, native to the region, was named the 'canary bird' after its island home, leading to the common misconception." }
        ],
        "whoWereThey": [
            { "name": "Audrey Hepburn", "bio": "A British actress and humanitarian. Recognized as a film and fashion icon, she was ranked by the American Film Institute as the third-greatest female screen legend." },
            { "name": "Franklin D. Roosevelt", "bio": "An American politician who served as the 32nd president of the United States from 1933 until his death in 1945. He directed the federal government during most of the Great Depression." },
            { "name": "Ralph Waldo Emerson", "bio": "An American essayist, lecturer, philosopher, and poet who led the transcendentalist movement of the mid-19th century." }
        ]
      },
      "he": {
        "quoteOfTheDay": [
          "שום דבר אינו בלתי אפשרי, המילה עצמה אומרת 'אני אפשרי'! – אודרי הפבורן",
          "הדבר היחיד שעלינו לפחד ממנו הוא הפחד עצמו. – פרנקלין ד. רוזוולט",
          "להיות עצמך בעולם שמנסה כל הזמן להפוך אותך למשהו אחר זה ההישג הגדול ביותר. – ראלף וולדו אמרסון"
        ],
        "interestingKnowledge": [
          { "title": "באלפבית ההוואי יש רק 12 אותיות", "text": "האלפבית ההוואי המסורתי, 'ka pīʻāpā Hawaiʻi', הוא אחד האלפביתים הקצרים בעולם, ומורכב מחמש תנועות ושבעה עיצורים בלבד. כל מילה בהוואית מסתיימת בתנועה, וההברות פשוטות, מה שמעניק לשפה את צלילה המלודי והזורם. מערכת יעילה זו הופכת את השפה לעקבית מבחינה פונטית וקלה יחסית להגייה, ומשקפת תרבות המעריכה בהירות והרמוניה בתקשורת." },
          { "title": "קבוצת פלמינגו נקראת 'Flamboyance'", "text": "מונח צבעוני והולם זה לוכד בצורה מושלמת את מהותן של ציפורים תוססות וחברתיות אלו. השפה האנגלית עשירה בשמות קיבוציים פואטיים כאלה לבעלי חיים, כאשר כל אחד מהם משקף מאפיין ייחודי של המין. לדוגמה, ניתן להיתקל ב'התרסקות' של קרנפים, 'פרלמנט' של ינשופים, או 'רצח' של עורבים. מונחים אלה מוסיפים רובד של יצירתיות והיסטוריה לאופן שבו אנו מתארים את עולם הטבע." },
          { "title": "המדבר הגדול בעולם הוא אנטארקטיקה", "text": "בעוד שאנו נוטים לקשר מדבריות לחום ודיונות חול, ההגדרה הטכנית של מדבר היא אזור שמקבל מעט מאוד משקעים. על פי מדד זה, המדבר הקוטבי האנטארקטי הוא המדבר הגדול ביותר על פני כדור הארץ. הוא גם המדבר הקר, היבש והגבוה ביותר. האוויר הקפוא אינו מסוגל להחזיק לחות רבה, וכתוצאה מכך כמות המשקעים השנתית נמוכה מאוד, היורדת כמעט כולה כשלג, ובכך מאתגרת את הדימוי המקובל שלנו של נוף מדברי." },
          { "title": "קליאופטרה לא הייתה מצרית", "text": "למרות היותה אחת השליטות המפורסמות ביותר של מצרים, קליאופטרה השביעית לא הייתה ממוצא מצרי. היא הייתה השליטה הפעילה האחרונה של הממלכה התלמיית, שושלת שנוסדה על ידי גנרל יווני מקדוני שהיה בן לווייתו של אלכסנדר הגדול. בעוד ששושלת משפחתה הייתה יוונית, קליאופטרה אימצה לחלוטין את התרבות המצרית והייתה חריגה נדירה בשושלתה בכך שהייתה הראשונה שלמדה את השפה המצרית. היטמעות תרבותית זו, בשילוב עם תבונתה הפוליטית, הפכה אותה למנהיגה אהובה בקרב עמה." },
          { "title": "האיים הקנריים נקראים על שם כלבים, לא ציפורים", "text": "שמו של ארכיפלג ספרדי פופולרי זה מקורו במפתיע ואין לו כל קשר לציפור השיר הצהובה. שם האיים נגזר מהביטוי הלטיני 'Canariae Insulae', שפירושו 'איי הכלבים'. שם זה ניתן על ידי חוקרים מוקדמים שנתקלו בזן של כלבים גדולים ועזים ('canes' בלטינית) באיים. רק מאוחר יותר נקראה הפרוש הקטן, יליד האזור, 'ציפור הקנרית' על שם אי מולדתו, מה שהוביל לתפיסה השגויה הנפוצה." }
        ],
        "whoWereThey": [
            { "name": "אודרי הפבורן", "bio": "שחקנית בריטית ופעילה הומניטרית. היא נחשבת לאייקון קולנוע ואופנה, ודורגה כשחקנית השלישית בגודלה בכל הזמנים על ידי מכון הסרטים האמקאי." },
            { "name": "פרנקלין ד. רוזוולט", "bio": "פוליטיקאי אמריקאי שכיהן כנשיא ה-32 של ארצות הברית מ-1933 ועד מותו ב-1945. הוא ניהל את הממשל הפדרלי במהלך רוב השפל הגדול." },
            { "name": "ראלף וולדו אמרסון", "bio": "מסאי, מרצה, פילוסוף ומשורר אמריקאי שהוביל את התנועה הטרנסצנדנטליסטית של אמצע המאה ה-19." }
        ]
      },
      "es": {
          "quoteOfTheDay": [
              "Nada es imposible, la propia palabra lo dice: '¡Soy posible'! – Audrey Hepburn",
              "Lo único que debemos temer es al miedo mismo. – Franklin D. Roosevelt",
              "Ser uno mismo en un mundo que constantemente intenta convertirte en otra cosa es el mayor logro. – Ralph Waldo Emerson"
          ],
          "interestingKnowledge": [
              { "title": "El alfabeto hawaiano tiene solo 12 letras", "text": "El alfabeto hawaiano tradicional, o 'ka pīʻāpā Hawaiʻi', es uno de los alfabetos más cortos del mundo, compuesto por solo cinco vocales y siete consonantes. Cada palabra en hawaiano termina en vocal y las sílabas son simples, lo que le da al idioma su sonido melódico. Este sistema simplificado hace que el idioma sea fonéticamente consistente y relativamente fácil de pronunciar una vez que se entienden las reglas básicas, lo que refleja una cultura que valora la claridad en la comunicación." },
              { "title": "Un grupo de flamencos se llama 'Flamboyance'", "text": "Este término colorido y apropiado captura la esencia de estas aves vibrantes y sociales, a menudo vistas juntas en grandes grupos. El idioma inglés es rico en sustantivos colectivos poéticos para animales, cada uno reflejando una característica única de la especie. Por ejemplo, podrías encontrar un 'crash' de rinocerontes, un 'parliament' de búhos, un 'murder' de cuervos o una 'ostentation' de pavos reales. Estos términos añaden una capa de creatividad e historia a la forma en que describimos el mundo natural." },
              { "title": "El desierto más grande del mundo es la Antártida", "text": "Aunque normalmente asociamos los desiertos con el calor abrasador, la definición técnica de un desierto es una región que recibe muy pocas precipitaciones. Según esta medida, el Desierto Polar Antártico es el desierto más grande de la Tierra, cubriendo un área de alrededor de 14 millones de kilómetros cuadrados. También es el desierto más frío, seco y alto del mundo. El aire gélido es incapaz de retener mucha humedad, lo que resulta en una precipitación anual de menos de 200 mm, que cae casi exclusivamente como nieve." },
              { "title": "Cleopatra no era egipcia", "text": "A pesar de ser una de las gobernantes más famosas de Egipto, Cleopatra VII no era de ascendencia egipcia. Fue la última gobernante activa del Reino Ptolemaico, una dinastía fundada por un general griego macedonio que fue compañero de Alejandro Magno. Aunque su linaje familiar era griego, Cleopatra abrazó por completo la cultura egipcia y fue una rara excepción en su dinastía por ser la primera en aprender el idioma egipcio. Esta inmersión cultural, combinada con su perspicacia política, la convirtió en una líder formidable y querida entre su pueblo." },
              { "title": "Las Islas Canarias llevan el nombre de perros, no de pájaros", "text": "El nombre de este archipiélago español tiene un origen sorprendente que no tiene nada que ver con el pájaro cantor amarillo. El nombre de las islas deriva de la frase latina 'Canariae Insulae', que se traduce como 'Islas de los Perros'. Según se informa, este nombre fue dado por los primeros exploradores que encontraron una especie de perros grandes y feroces ('canes' en latín) en las islas. Fue más tarde cuando el pequeño pinzón, nativo de la región, fue nombrado 'pájaro canario' por su hogar insular." }
          ],
          "whoWereThey": [
              { "name": "Audrey Hepburn", "bio": "Una actriz y humanitaria británica. Reconocida como un ícono del cine y la moda, fue clasificada por el American Film Institute como la tercera leyenda femenina más grande de la pantalla." },
              { "name": "Franklin D. Roosevelt", "bio": "Un político estadounidense que se desempeñó como el 32º presidente de los Estados Unidos desde 1933 hasta su muerte en 1945. Dirigió el gobierno federal durante la mayor parte de la Gran Depresión." },
              { "name": "Ralph Waldo Emerson", "bio": "Un ensayista, conferenciante, filósofo y poeta estadounidense que lideró el movimiento trascendentalista de mediados del siglo XIX." }
          ]
      },
      // FIX: The French content for Day 3 was incomplete and partially untranslated. This has been corrected.
      "fr": {
          "quoteOfTheDay": [
              "Rien n'est impossible, le mot lui-même dit 'Je suis possible' ! – Audrey Hepburn",
              "La seule chose que nous ayons à craindre, c'est la peur elle-même. – Franklin D. Roosevelt",
              "Être soi-même dans un monde qui essaie constamment de vous faire devenir autre chose est la plus grande des réussites. – Ralph Waldo Emerson"
          ],
          "interestingKnowledge": [
              { "title": "L'alphabet hawaïen ne compte que 12 lettres", "text": "L'alphabet hawaïen traditionnel, ou 'ka pīʻāpā Hawaiʻi', est l'un des alphabets les plus courts du monde, composé de seulement cinq voyelles (A, E, I, O, U) et sept consonnes (H, K, L, M, N, P, W). Chaque mot en hawaïen se termine par une voyelle, et les syllabes sont simples, ce qui donne à la langue son son mélodieux et fluide. Ce système rationalisé rend la langue phonétiquement cohérente et relativement facile à prononcer une fois les règles de base comprises, reflétant une culture qui valorise la clarté et l'harmonie dans la communication." },
              { "title": "Un groupe de flamants roses est appelé une 'Flamboyance'", "text": "Ce terme coloré et approprié capture parfaitement l'essence de ces oiseaux vibrants et sociaux, souvent vus pataugeant ensemble en grands groupes éblouissants. La langue anglaise est riche de tels noms collectifs poétiques pour les animaux, chacun reflétant souvent une caractéristique unique de l'espèce. Par exemple, on peut rencontrer un 'crash' de rhinocéros, un 'parlement' de hiboux à l'air sage, un 'meurtre' de corbeaux de mauvais augure, ou une 'ostentation' de paons. Ces termes ajoutent une couche de créativité et d'histoire à la façon dont nous décrivons le monde naturel." },
              { "title": "Le plus grand désert du monde est l'Antarctique", "text": "Bien que nous associons généralement les déserts à une chaleur torride et à de vastes dunes de sable, la définition technique d'un désert est une région qui reçoit très peu de précipitations. Selon cette mesure, le désert polaire antarctique est le plus grand désert de la Terre, couvrant une superficie d'environ 14 millions de kilomètres carrés. C'est aussi le désert le plus froid, le plus sec et le plus élevé du monde. L'air glacial est incapable de retenir beaucoup d'humidité, ce qui entraîne des précipitations annuelles de moins de 200 mm, qui tombent presque exclusivement sous forme de neige, remettant en question notre image conventionnelle d'un paysage désertique." },
              { "title": "Cléopâtre n'était pas égyptienne", "text": "Bien qu'elle soit l'une des dirigeantes les plus célèbres d'Égypte, Cléopâtre VII n'était pas d'ascendance égyptienne. Elle était la dernière dirigeante active du royaume ptolémaïque, une dynastie fondée par un général grec macédonien qui était un compagnon d'Alexandre le Grand. Alors que sa lignée familiale était grecque, Cléopâtre a pleinement embrassé la culture égyptienne et a été une rare exception dans sa dynastie en étant la première à apprendre la langue égyptienne. Cette immersion culturelle, combinée à son sens politique, a fait d'elle une dirigeante redoutable et aimée de son peuple." },
              { "title": "Les îles Canaries doivent leur nom aux chiens, pas aux oiseaux", "text": "Le nom de ce populaire archipel espagnol a une origine surprenante qui n'a rien à voir avec le joyeux oiseau chanteur jaune. Le nom des îles dérive de l'expression latine 'Canariae Insulae', qui se traduit par 'îles des chiens'. Ce nom aurait été donné par les premiers explorateurs qui ont rencontré une espèce de grands chiens féroces ('canes' en latin) sur les îles. Ce n'est que plus tard que le petit pinson, originaire de la région, a été nommé 'canari' d'après son île d'origine, ce qui a conduit à cette idée fausse courante." }
          ],
          "whoWereThey": [
              { "name": "Audrey Hepburn", "bio": "Une actrice et humanitaire britannique. Reconnue comme une icône du cinéma et de la mode, elle a été classée par l'American Film Institute comme la troisième plus grande légende féminine de l'écran." },
              { "name": "Franklin D. Roosevelt", "bio": "Un homme politique américain qui a été le 32e président des États-Unis de 1933 jusqu'à sa mort en 1945. Il a dirigé le gouvernement fédéral pendant la majeure partie de la Grande Dépression." },
              { "name": "Ralph Waldo Emerson", "bio": "Un essayiste, conférencier, philosophe et poète américain qui a dirigé le mouvement transcendantaliste du milieu du XIXe siècle." }
          ]
      },
      "de": {
          "quoteOfTheDay": [
              "Nichts ist unmöglich, das Wort selbst sagt 'Ich bin möglich'! – Audrey Hepburn",
              "Das Einzige, was wir zu fürchten haben, ist die Furcht selbst. – Franklin D. Roosevelt",
              "In einer Welt, die ständig versucht, dich zu etwas anderem zu machen, du selbst zu sein, ist die größte Leistung. – Ralph Waldo Emerson"
          ],
          "interestingKnowledge": [
              { "title": "Das hawaiianische Alphabet hat nur 12 Buchstaben", "text": "Das traditionelle hawaiianische Alphabet, oder 'ka pīʻāpā Hawaiʻi', ist eines der kürzesten Alphabete der Welt und besteht aus nur fünf Vokalen und sieben Konsonanten. Jedes Wort im Hawaiianischen endet auf einem Vokal und die Silben sind einfach, was der Sprache ihren melodischen Klang verleiht. Dieses System macht die Sprache phonetisch konsistent und relativ leicht auszusprechen, was eine Kultur widerspiegelt, die Klarheit in der Kommunikation schätzt." },
              { "title": "Eine Gruppe von Flamingos wird 'Flamboyance' genannt", "text": "Dieser farbenfrohe und passende Begriff fängt die Essenz dieser lebhaften, sozialen Vögel ein, die oft in großen Gruppen zusammen gesehen werden. Die englische Sprache ist reich an solchen poetischen Sammelbegriffen für Tiere, von denen jeder eine einzigartige Eigenschaft der Art widerspiegelt. Zum Beispiel könnten Sie einem 'Crash' von Nashörnern, einem 'Parlament' von Eulen, einem 'Mord' von Krähen oder einer 'Präsentation' von Pfauen begegnen. Diese Begriffe fügen der Art und Weise, wie wir die Natur beschreiben, eine Ebene der Kreativität und Geschichte hinzu." },
              { "title": "Die größte Wüste der Welt ist die Antarktis", "text": "Obwohl wir Wüsten normalerweise mit sengender Hitze in Verbindung bringen, ist die technische Definition einer Wüste eine Region, die sehr wenig Niederschlag erhält. Nach diesem Maßstab ist die Antarktische Polarwüste die größte Wüste der Erde und bedeckt eine Fläche von rund 14 Millionen Quadratkilometern. Sie ist auch die kälteste, trockenste und höchste Wüste der Welt. Die eisige Luft kann nicht viel Feuchtigkeit halten, was zu einem jährlichen Niederschlag von weniger als 200 mm führt, der fast ausschließlich als Schnee fällt." },
              { "title": "Kleopatra war keine Ägypterin", "text": "Obwohl sie eine der berühmtesten Herrscherinnen Ägyptens war, war Kleopatra VII. nicht ägyptischer Abstammung. Sie war die letzte aktive Herrscherin des Ptolemäerreichs, einer Dynastie, die von einem mazedonisch-griechischen General gegründet wurde, der ein Gefährte Alexanders des Großen war. Obwohl ihre Familienlinie griechisch war, nahm Kleopatra die ägyptische Kultur voll an und war eine seltene Ausnahme in ihrer Dynastie, da sie die erste war, die die ägyptische Sprache lernte. Diese kulturelle Immersion, kombiniert mit ihrem politischen Scharfsinn, machte sie zu einer beeindruckenden und beliebten Anführerin." },
              { "title": "Die Kanarischen Inseln sind nach Hunden benannt, nicht nach Vögeln", "text": "Der Name dieses beliebten spanischen Archipels hat einen überraschenden Ursprung, der nichts mit dem fröhlichen gelben Singvogel zu tun hat. Der Name der Inseln leitet sich von dem lateinischen Ausdruck 'Canariae Insulae' ab, was 'Inseln der Hunde' bedeutet. Dieser Name wurde Berichten zufolge von frühen Entdeckern vergeben, die auf den Inseln eine Art großer, wilder Hunde ('canes' auf Latein) antrafen. Erst später wurde der kleine, in der Region heimische Fink nach seiner Inselheimat 'Kanarienvogel' genannt." }
          ],
          "whoWereThey": [
              { "name": "Audrey Hepburn", "bio": "Eine britische Schauspielerin und humanitäre Helferin. Als Film- und Modeikone anerkannt, wurde sie vom American Film Institute als die drittgrößte weibliche Leinwandlegende eingestuft." },
              { "name": "Franklin D. Roosevelt", "bio": "Ein amerikanischer Politiker, der von 1933 bis zu seinem Tod 1945 als 32. Präsident der Vereinigten Staaten diente. Er leitete die Bundesregierung während des größten Teils der Weltwirtschaftskrise." },
              { "name": "Ralph Waldo Emerson", "bio": "Ein amerikanischer Essayist, Dozent, Philosoph und Dichter, der die transzendentalistische Bewegung Mitte des 19. Jahrhunderts anführte." }
          ]
      },
      "tr": {
          "quoteOfTheDay": [
              "Hiçbir şey imkansız değildir, kelimenin kendisi 'Ben mümkünün' der! – Audrey Hepburn",
              "Korkmamız gereken tek şey korkunun kendisidir. – Franklin D. Roosevelt",
              "Sürekli olarak sizi başka bir şeye dönüştürmeye çalışan bir dünyada kendiniz olmak en büyük başarıdır. – Ralph Waldo Emerson"
          ],
          "interestingKnowledge": [
              { "title": "Hawaii Alfabesinde Sadece 12 Harf Vardır", "text": "Geleneksel Hawaii alfabesi veya 'ka pīʻāpā Hawaiʻi', dünyanın en kısa alfabelerinden biridir ve sadece beş ünlü ve yedi ünsüzden oluşur. Hawaii dilindeki her kelime bir ünlü ile biter ve heceler basittir, bu da dile melodik sesini verir. Bu sistem, dili fonetik olarak tutarlı ve anlaşılması nispeten kolay hale getirir, bu da iletişimde netliği değerlendiren bir kültürü yansıtır." },
              { "title": "Bir Flamingo Grubuna 'Flamboyance' Denir", "text": "Bu renkli ve uygun terim, genellikle büyük gruplar halinde bir arada görülen bu canlı, sosyal kuşların özünü yakalar. İngilizce, her biri türün benzersiz bir özelliğini yansıtan hayvanlar için bu tür şiirsel topluluk isimleriyle zengindir. Örneğin, bir 'gergedan çarpışması', bir 'baykuş parlamentosu', bir 'karga cinayeti' veya bir 'tavus kuşu gösterişi' ile karşılaşabilirsiniz. Bu terimler, doğal dünyayı tanımlama şeklimize bir yaratıcılık ve tarih katmanı ekler." },
              { "title": "Dünyanın En Büyük Çölü Antarktika'dır", "text": "Çölleri genellikle kavurucu sıcaklıkla ilişkilendirsek de, bir çölün teknik tanımı çok az yağış alan bir bölgedir. Bu ölçüye göre, Antarktik Kutup Çölü, yaklaşık 14 milyon kilometrekarelik bir alanı kaplayan Dünya'nın en büyük çölüdür. Aynı zamanda dünyanın en soğuk, en kurak ve en yüksek çölüdür. Soğuk hava fazla nem tutamaz, bu da yıllık 200 mm'den az yağışla sonuçlanır ve bu yağış neredeyse tamamen kar olarak düşer." },
              { "title": "Kleopatra Mısırlı Değildi", "text": "Mısır'ın en ünlü hükümdarlarından biri olmasına rağmen, VII. Kleopatra Mısır kökenli değildi. O, Büyük İskender'in bir yoldaşı olan Makedon bir Yunan general tarafından kurulan Ptolemaios Krallığı'nın son aktif hükümdarıydı. Aile soyu Yunan olmasına rağmen, Kleopatra Mısır kültürünü tamamen benimsedi ve hanedanlığında Mısır dilini öğrenen ilk kişi olarak nadir bir istisnaydı. Bu kültürel bütünleşme, siyasi zekasıyla birleştiğinde, onu halkı arasında müthiş ve sevilen bir lider yaptı." },
              { "title": "Kanarya Adaları Adını Kuşlardan Değil, Köpeklerden Almıştır", "text": "Bu popüler İspanyol takımadalarının adı, neşeli sarı öten kuşla ilgisi olmayan şaşırtıcı bir kökene sahiptir. Adaların adı, 'Köpeklerin Adaları' anlamına gelen Latince 'Canariae Insulae' ifadesinden türemiştir. Bu adın, adalarda büyük, vahşi bir köpek türüyle ('canes' Latince'de) karşılaşan ilk kaşifler tarafından verildiği bildirilmektedir. Daha sonra bölgeye özgü olan küçük ispinoz, ada evinden sonra 'kanarya kuşu' olarak adlandırıldı." }
          ],
          "whoWereThey": [
              { "name": "Audrey Hepburn", "bio": "İngiliz bir aktris ve insani yardımsever. Bir film ve moda ikonu olarak tanınan Hepburn, Amerikan Film Enstitüsü tarafından üçüncü en büyük kadın ekran efsanesi olarak sıralandı." },
              { "name": "Franklin D. Roosevelt", "bio": "1933'ten 1945'teki ölümüne kadar Amerika Birleşik Devletleri'nin 32. başkanı olarak görev yapan Amerikalı bir politikacı. Büyük Buhran'ın büyük bölümünde federal hükümeti yönetti." },
              { "name": "Ralph Waldo Emerson", "bio": "19. yüzyılın ortalarındaki transandantalist harekete öncülük eden Amerikalı bir denemeci, öğretim görevlisi, filozof ve şair." }
          ]
      }
    }
  }
];
